package com.aylar.chatty.ui.components


data class CountryPhoneCode(
    val code: String,
    val countryCode: String,
    val countryName: String,
    val format: String,
    val flagEmoji: String
)

val countryPhoneCodes = listOf(
    CountryPhoneCode("998", "UZ", "Uzbekistan", "XX XXXXXXX", "🇺🇿"),
    CountryPhoneCode("996", "KG", "Kyrgyzstan", "XXX XXXXXX", "🇰🇬"),
    CountryPhoneCode("995", "GE", "Georgia", "XXX XXX XXX", "🇬🇪"),
    CountryPhoneCode("994", "AZ", "Azerbaijan", "XX XXX XXXX", "🇦🇿"),
    CountryPhoneCode("993", "TM", "Turkmenistan", "XX XXXXXX", "🇹🇲"),
    CountryPhoneCode("992", "TJ", "Tajikistan", "XX XXX XXXX", "🇹🇯"),
    CountryPhoneCode("977", "NP", "Nepal", "XX XXXX XXXX", "🇳🇵"),
    CountryPhoneCode("976", "MN", "Mongolia", "XX XX XXXX", "🇲🇳"),
    CountryPhoneCode("975", "BT", "Bhutan", "XX XXX XXX", "🇧🇹"),
    CountryPhoneCode("974", "QA", "Qatar", "XX XXX XXX", "🇶🇦"),
    CountryPhoneCode("973", "BH", "Bahrain", "XXXX XXXX", "🇧🇭"),
    CountryPhoneCode("972", "IL", "Israel", "XX XXX XXXX", "🇮🇱"),
    CountryPhoneCode("971", "AE", "United Arab Emirates", "XX XXX XXXX", "🇦🇪"),
    CountryPhoneCode("970", "PS", "Palestine", "XXX XX XXXX", "🇵🇸"),
    CountryPhoneCode("968", "OM", "Oman", "XXXX XXXX", "🇴🇲"),
    CountryPhoneCode("967", "YE", "Yemen", "XXX XXX XXX", "🇾🇪"),
    CountryPhoneCode("966", "SA", "Saudi Arabia", "XX XXX XXXX", "🇸🇦"),
    CountryPhoneCode("965", "KW", "Kuwait", "XXXX XXXX", "🇰🇼"),
    CountryPhoneCode("964", "IQ", "Iraq", "XXX XXX XXXX", "🇮🇶"),
    CountryPhoneCode("963", "SY", "Syria", "XXX XXX XXX", "🇸🇾"),
    CountryPhoneCode("962", "JO", "Jordan", "X XXXX XXXX", "🇯🇴"),
    CountryPhoneCode("961", "LB", "Lebanon", "XXX XXXX", "🇱🇧"),
    CountryPhoneCode("960", "MV", "Maldives", "XXX XXXX", "🇲🇻"),
    CountryPhoneCode("888", "FT", "Anonymous Numbers", "XXXX XXXX", "🏳️‍🌈"),
    CountryPhoneCode("886", "TW", "Taiwan", "XXX XXX XXX", "🇹🇼"),
    CountryPhoneCode("883", "GO", "International Networks", "XXXX XXXX", "🌍"),
    CountryPhoneCode("882", "GO", "International Networks", "XXXX XXXX", "🌍"),
    CountryPhoneCode("881", "GO", "Global Mobile Satellite", "XXXX XXXX", "🌍"),
    CountryPhoneCode("880", "BD", "Bangladesh", "", "🇧🇩"),
    CountryPhoneCode("856", "LA", "Laos", "XX XX XXX XXX", "🇱🇦"),
    CountryPhoneCode("855", "KH", "Cambodia", "", "🇰🇭"),
    CountryPhoneCode("853", "MO", "Macau", "XXXX XXXX", "🇲🇴"),
    CountryPhoneCode("852", "HK", "Hong Kong", "X XXX XXXX", "🇭🇰"),
    CountryPhoneCode("850", "KP", "North Korea", "", "🇰🇵"),
    CountryPhoneCode("692", "MH", "Marshall Islands", "", "🇲🇭"),
    CountryPhoneCode("691", "FM", "Micronesia", "", "🇫🇲"),
    CountryPhoneCode("690", "TK", "Tokelau", "", "🇹🇰"),
    CountryPhoneCode("689", "PF", "French Polynesia", "", "🇵🇫"),
    CountryPhoneCode("688", "TV", "Tuvalu", "", "🇹🇻"),
    CountryPhoneCode("687", "NC", "New Caledonia", "", "🇳🇨"),
    CountryPhoneCode("686", "KI", "Kiribati", "", "🇰🇮"),
    CountryPhoneCode("685", "WS", "Samoa", "", "🇼🇸"),
    CountryPhoneCode("683", "NU", "Niue", "", "🇳🇺"),
    CountryPhoneCode("682", "CK", "Cook Islands", "", "🇨🇰"),
    CountryPhoneCode("681", "WF", "Wallis & Futuna", "", "🇼🇫"),
    CountryPhoneCode("680", "PW", "Palau", "", "🇵🇼"),
    CountryPhoneCode("679", "FJ", "Fiji", "", "🇫🇯"),
    CountryPhoneCode("678", "VU", "Vanuatu", "", "🇻🇺"),
    CountryPhoneCode("677", "SB", "Solomon Islands", "", "🇸🇧"),
    CountryPhoneCode("676", "TO", "Tonga", "", "🇹🇴"),
    CountryPhoneCode("675", "PG", "Papua New Guinea", "", "🇵🇬"),
    CountryPhoneCode("674", "NR", "Nauru", "", "🇳🇷"),
    CountryPhoneCode("673", "BN", "Brunei Darussalam", "XXX XXXX", "🇧🇳"),
    CountryPhoneCode("672", "NF", "Norfolk Island", "", "🇳🇫"),
    CountryPhoneCode("670", "TL", "Timor-Leste", "", "🇹🇱"),
    CountryPhoneCode("599", "BQ", "Bonaire, Sint Eustatius & Saba", "", "🇧🇶"),
    CountryPhoneCode("599", "CW", "Curaçao", "", "🇨🇼"),
    CountryPhoneCode("598", "UY", "Uruguay", "X XXX XXXX", "🇺🇾"),
    CountryPhoneCode("597", "SR", "Suriname", "XXX XXXX", "🇸🇷"),
    CountryPhoneCode("596", "MQ", "Martinique", "", "🇲🇶"),
    CountryPhoneCode("595", "PY", "Paraguay", "XXX XXX XXX", "🇵🇾"),
    CountryPhoneCode("594", "GF", "French Guiana", "", "🇬🇫"),
    CountryPhoneCode("593", "EC", "Ecuador", "XX XXX XXXX", "🇪🇨"),
    CountryPhoneCode("592", "GY", "Guyana", "", "🇬🇾"),
    CountryPhoneCode("591", "BO", "Bolivia", "X XXX XXXX", "🇧🇴"),
    CountryPhoneCode("590", "GP", "Guadeloupe", "XXX XX XX XX", "🇬🇺"),
    CountryPhoneCode("509", "HT", "Haiti", "", "🇭🇹"),
    CountryPhoneCode("508", "PM", "Saint Pierre & Miquelon", "", "🇵🇲"),
    CountryPhoneCode("507", "PA", "Panama", "XXXX XXXX", "🇵🇦"),
    CountryPhoneCode("506", "CR", "Costa Rica", "XXXX XXXX", "🇨🇷"),
    CountryPhoneCode("505", "NI", "Nicaragua", "XXXX XXXX", "🇳🇮"),
    CountryPhoneCode("504", "HN", "Honduras", "XXXX XXXX", "🇭🇳"),
    CountryPhoneCode("503", "SV", "El Salvador", "XXXX XXXX", "🇸🇻"),
    CountryPhoneCode("502", "GT", "Guatemala", "X XXX XXXX", "🇬🇹"),
    CountryPhoneCode("501", "BZ", "Belize", "", "🇧🇿"),
    CountryPhoneCode("500", "FK", "Falkland Islands", "", "🇫🇰"),
    CountryPhoneCode("423", "LI", "Liechtenstein", "", "🇱🇮"),
    CountryPhoneCode("421", "SK", "Slovakia", "XXX XXX XXX", "🇸🇰"),
    CountryPhoneCode("420", "CZ", "Czech Republic", "XXX XXX XXX", "🇨🇿"),
    CountryPhoneCode("389", "MK", "Macedonia", "XX XXX XXX", "🇲🇰"),
    CountryPhoneCode("387", "BA", "Bosnia & Herzegovina", "XX XXX XXX", "🇧🇦"),
    CountryPhoneCode("386", "SI", "Slovenia", "XX XXX XXX", "🇸🇮"),
    CountryPhoneCode("385", "HR", "Croatia", "", "🇭🇷"),
    CountryPhoneCode("383", "XK", "Kosovo", "XXXX XXXX", "🇽🇰"),
    CountryPhoneCode("382", "ME", "Montenegro", "", "🇲🇪"),
    CountryPhoneCode("381", "RS", "Serbia", "XX XXX XXXX", "🇷🇸"),
    CountryPhoneCode("380", "UA", "Ukraine", "XX XXX XX XX", "🇺🇦"),
    CountryPhoneCode("378", "SM", "San Marino", "XXX XXX XXXX", "🇸🇲"),
    CountryPhoneCode("377", "MC", "Monaco", "XXXX XXXX", "🇲🇨"),
    CountryPhoneCode("376", "AD", "Andorra", "XX XX XX", "🇦🇩"),
    CountryPhoneCode("375", "BY", "Belarus", "XX XXX XXXX", "🇧🇾"),
    CountryPhoneCode("374", "AM", "Armenia", "XX XXX XXX", "🇦🇲"),
    CountryPhoneCode("373", "MD", "Moldova", "XX XXX XXX", "🇲🇩"),
    CountryPhoneCode("372", "EE", "Estonia", "", "🇪🇪"),
    CountryPhoneCode("371", "LV", "Latvia", "XXX XXXXX", "🇱🇻"),
    CountryPhoneCode("370", "LT", "Lithuania", "XXX XXXXX", "🇱🇹"),
    CountryPhoneCode("359", "BG", "Bulgaria", "", "🇧🇬"),
    CountryPhoneCode("358", "FI", "Finland", "", "🇫🇮"),
    CountryPhoneCode("357", "CY", "Cyprus", "XXXX XXXX", "🇨🇾"),
    CountryPhoneCode("356", "MT", "Malta", "XX XX XX XX", "🇲🇹"),
    CountryPhoneCode("355", "AL", "Albania", "XX XXX XXXX", "🇦🇱"),
    CountryPhoneCode("354", "IS", "Iceland", "XXX XXXX", "🇮🇸"),
    CountryPhoneCode("353", "IE", "Ireland", "XX XXX XXXX", "🇮🇪"),
    CountryPhoneCode("352", "LU", "Luxembourg", "", "🇱🇺"),
    CountryPhoneCode("351", "PT", "Portugal", "X XXXX XXXX", "🇵🇹"),
    CountryPhoneCode("350", "GI", "Gibraltar", "XXXX XXXX", "🇬🇮"),
    CountryPhoneCode("299", "GL", "Greenland", "XXX XXX", "🇬🇱"),
    CountryPhoneCode("298", "FO", "Faroe Islands", "XXX XXX", "🇫🇴"),
    CountryPhoneCode("297", "AW", "Aruba", "XXX XXXX", "🇦🇼"),
    CountryPhoneCode("291", "ER", "Eritrea", "X XXX XXX", "🇪🇷"),
    CountryPhoneCode("290", "SH", "Saint Helena", "XX XXX", "🇸🇭"),
    CountryPhoneCode("269", "KM", "Comoros", "XXX XXXX", "🇰🇲"),
    CountryPhoneCode("268", "SZ", "Swaziland", "XXXX XXXX", "🇸🇿"),
    CountryPhoneCode("267", "BW", "Botswana", "XX XXX XXX", "🇧🇼"),
    CountryPhoneCode("266", "LS", "Lesotho", "XX XXX XXX", "🇱🇸"),
    CountryPhoneCode("265", "MW", "Malawi", "77 XXX XXXX", "🇲🇼"),
    CountryPhoneCode("264", "NA", "Namibia", "XX XXX XXXX", "🇳🇦"),
    CountryPhoneCode("263", "ZW", "Zimbabwe", "XX XXX XXXX", "🇿🇼"),
    CountryPhoneCode("262", "RE", "Réunion", "XXX XXX XXX", "🇷🇪"),
    CountryPhoneCode("261", "MG", "Madagascar", "XX XX XXX XX", "🇲🇬"),
    CountryPhoneCode("260", "ZM", "Zambia", "XX XXX XXXX", "🇿🇲"),
    CountryPhoneCode("258", "MZ", "Mozambique", "XX XXX XXXX", "🇲🇿"),
    CountryPhoneCode("257", "BI", "Burundi", "XX XX XXXX", "🇧🇮"),
    CountryPhoneCode("256", "UG", "Uganda", "XX XXX XXXX", "🇺🇬"),
    CountryPhoneCode("255", "TZ", "Tanzania", "XX XXX XXXX", "🇹🇿"),
    CountryPhoneCode("254", "KE", "Kenya", "XXX XXX XXX", "🇰🇪"),
    CountryPhoneCode("253", "DJ", "Djibouti", "XX XX XX XX", "🇩🇯"),
    CountryPhoneCode("252", "SO", "Somalia", "XX XXX XXX", "🇸🇴"),
    CountryPhoneCode("251", "ET", "Ethiopia", "XX XXX XXXX", "🇪🇹"),
    CountryPhoneCode("250", "RW", "Rwanda", "XXX XXX XXX", "🇷🇼"),
    CountryPhoneCode("249", "SD", "Sudan", "XX XXX XXXX", "🇸🇩"),
    CountryPhoneCode("248", "SC", "Seychelles", "X XX XX XX", "🇸🇨"),
    CountryPhoneCode("247", "SH", "Saint Helena", "XXXX", "🇸🇭"),
    CountryPhoneCode("246", "IO", "Diego Garcia", "XXX XXXX", "🇮🇴"),
    CountryPhoneCode("245", "GW", "Guinea-Bissau", "XXX XXXX", "🇬🇼"),
    CountryPhoneCode("244", "AO", "Angola", "XXX XXX XXX", "🇦🇴"),
    CountryPhoneCode("243", "CD", "Congo (Dem. Rep.)", "XX XXX XXXX", "🇨🇩"),
    CountryPhoneCode("242", "CG", "Congo (Rep.)", "XX XXX XXXX", "🇨🇬"),
    CountryPhoneCode("241", "GA", "Gabon", "X XX XX XX", "🇬🇦"),
    CountryPhoneCode("240", "GQ", "Equatorial Guinea", "XXX XXX XXX", "🇬🇶"),
    CountryPhoneCode("239", "ST", "São Tomé & Príncipe", "XX XXXXX", "🇸🇹"),
    CountryPhoneCode("238", "CV", "Cape Verde", "XXX XXXX", "🇨🇻"),
    CountryPhoneCode("237", "CM", "Cameroon", "XXXX XXXX", "🇨🇲"),
    CountryPhoneCode("236", "CF", "Central African Rep.", "XX XX XX XX", "🇨🇫"),
    CountryPhoneCode("235", "TD", "Chad", "XX XX XX XX", "🇹🇩"),
    CountryPhoneCode("234", "NG", "Nigeria", "XXX XXX XXXX", "🇳🇬"),
    CountryPhoneCode("233", "GH", "Ghana", "XX XXX XXX", "🇬🇭"),
    CountryPhoneCode("232", "SL", "Sierra Leone", "XX XXX XXX", "🇸🇱"),
    CountryPhoneCode("231", "LR", "Liberia", "XX XXX XXX", "🇱🇷"),
    CountryPhoneCode("230", "MU", "Mauritius", "XX XXX XXX", "🇲🇺"),
    CountryPhoneCode("229", "BJ", "Benin", "XX XXX XXX", "🇧🇯"),
    CountryPhoneCode("228", "TG", "Togo", "XX XXX XXX", "🇹🇬"),
    CountryPhoneCode("227", "NE", "Niger", "XX XX XX XX", "🇳🇪"),
    CountryPhoneCode("226", "BF", "Burkina Faso", "XX XX XX XX", "🇧🇫"),
    CountryPhoneCode("225", "CI", "Côte d'Ivoire", "XX XXX XXX", "🇨🇮"),
    CountryPhoneCode("224", "GN", "Guinea", "XXX XXX XXX", "🇬🇳"),
    CountryPhoneCode("223", "ML", "Mali", "XXXX XXXX", "🇲🇱"),
    CountryPhoneCode("222", "MR", "Mauritania", "XXXX XXXX", "🇲🇷"),
    CountryPhoneCode("221", "SN", "Senegal", "XX XXX XXXX", "🇸🇳"),
    CountryPhoneCode("220", "GM", "Gambia", "XXX XXXX", "🇬🇲"),
    CountryPhoneCode("218", "LY", "Libya", "XX XXX XXXX", "🇱🇾"),
    CountryPhoneCode("216", "TN", "Tunisia", "XX XXX XXX", "🇹🇳"),
    CountryPhoneCode("213", "DZ", "Algeria", "XXX XX XX XX", "🇩🇿"),
    CountryPhoneCode("212", "MA", "Morocco", "XX XXX XXXX", "🇲🇦"),
    CountryPhoneCode("211", "SS", "South Sudan", "XX XXX XXXX", "🇸🇸"),
    CountryPhoneCode("98", "IR", "Iran", "XXX XXX XXXX", "🇮🇷"),
    CountryPhoneCode("95", "MM", "Myanmar", "XXX XXX XXXX", "🇲🇲"),
    CountryPhoneCode("94", "LK", "Sri Lanka", "XX XXX XXXX", "🇱🇰"),
    CountryPhoneCode("93", "AF", "Afghanistan", "XXX XXX XXX", "🇦🇫"),
    CountryPhoneCode("92", "PK", "Pakistan", "XXX XXX XXXX", "🇵🇰"),
    CountryPhoneCode("91", "IN", "India", "XXXXX XXXXX", "🇮🇳"),
    CountryPhoneCode("90", "TR", "Turkey", "XXX XXX XXXX", "🇹🇷"),
    CountryPhoneCode("86", "CN", "China", "XXX XXXX XXXX", "🇨🇳"),
    CountryPhoneCode("84", "VN", "Vietnam", "XXX XXXX XXXX", "🇻🇳"),
    CountryPhoneCode("82", "KR", "South Korea", "XXX XXXX XXXX", "🇰🇷"),
    CountryPhoneCode("81", "JP", "Japan", "XX XXXX XXXX", "🇯🇵"),
    CountryPhoneCode("66", "TH", "Thailand", "X XXXX XXXX", "🇹🇭"),
    CountryPhoneCode("65", "SG", "Singapore", "XXXX XXXX", "🇸🇬"),
    CountryPhoneCode("64", "NZ", "New Zealand", "XXX XXX XXXX", "🇳🇿"),
    CountryPhoneCode("63", "PH", "Philippines", "XXX XXX XXXX", "🇵🇭"),
    CountryPhoneCode("62", "ID", "Indonesia", "XXX XXX XXXX", "🇮🇩"),
    CountryPhoneCode("61", "AU", "Australia", "XXX XXX XXX", "🇦🇺"),
    CountryPhoneCode("60", "MY", "Malaysia", "XXX XXX XXXX", "🇲🇾"),
    CountryPhoneCode("58", "VE", "Venezuela", "XXX XXX XXXX", "🇻🇪"),
    CountryPhoneCode("57", "CO", "Colombia", "XXX XXX XXXX", "🇨🇴"),
    CountryPhoneCode("56", "CL", "Chile", "X XXXX XXXX", "🇨🇱"),
    CountryPhoneCode("55", "BR", "Brazil", "XX XXXXX XXXX", "🇧🇷"),
    CountryPhoneCode("54", "AR", "Argentina", "XX XXX XXXX", "🇦🇷"),
    CountryPhoneCode("53", "CU", "Cuba", "XXXX XXXX", "🇨🇺"),
    CountryPhoneCode("52", "MX", "Mexico", "XXX XXX XXXX", "🇲🇽"),
    CountryPhoneCode("51", "PE", "Peru", "XXX XXX XXX", "🇵🇪"),
    CountryPhoneCode("49", "DE", "Germany", "XXX XXX XXX", "🇩🇪"),
    CountryPhoneCode("48", "PL", "Poland", "XXX XXX XXX", "🇵🇱"),
    CountryPhoneCode("47", "NO", "Norway", "XXXX XXXX", "🇳🇴"),
    CountryPhoneCode("46", "SE", "Sweden", "XX XXX XXXX", "🇸🇪"),
    CountryPhoneCode("45", "DK", "Denmark", "XXXX XXXX", "🇩🇰"),
    CountryPhoneCode("44", "GB", "United Kingdom", "XXXX XXXXXX", "🇬🇧"),
    CountryPhoneCode("43", "AT", "Austria", "XXX XXX XXX", "🇦🇹"),
    CountryPhoneCode("41", "CH", "Switzerland", "XX XXX XXXX", "🇨🇭"),
    CountryPhoneCode("40", "RO", "Romania", "XXX XXX XXX", "🇷🇴"),
    CountryPhoneCode("39", "IT", "Italy", "XX XXX XXXX", "🇮🇹"),
    CountryPhoneCode("36", "HU", "Hungary", "XXX XXX XXX", "🇭🇺"),
    CountryPhoneCode("34", "ES", "Spain", "XXX XXX XXX", "🇪🇸"),
    CountryPhoneCode("33", "FR", "France", "X XX XX XX XX", "🇫🇷"),
    CountryPhoneCode("32", "BE", "Belgium", "XXX XX XX XX", "🇧🇪"),
    CountryPhoneCode("31", "NL", "Netherlands", "X XX XX XX XX", "🇳🇱"),
    CountryPhoneCode("30", "GR", "Greece", "XXX XXX XXXX", "🇬🇷"),
    CountryPhoneCode("27", "ZA", "South Africa", "XX XXX XXXX", "🇿🇦"),
    CountryPhoneCode("20", "EG", "Egypt", "XX XXXX XXXX", "🇪🇬"),
    CountryPhoneCode("7", "KZ", "Kazakhstan", "XXX XXX XX XX", "🇰🇿"),
    CountryPhoneCode("7", "RU", "Russian Federation", "XXX XXX XXXX", "🇷🇺"),
    CountryPhoneCode("1", "PR", "Puerto Rico", "XXX XXX XXXX", "🇵🇷"),
    CountryPhoneCode("1", "DO", "Dominican Rep.", "XXX XXX XXXX", "🇩🇴"),
    CountryPhoneCode("1", "CA", "Canada", "XXX XXX XXXX", "🇨🇦"),
    CountryPhoneCode("1", "US", "USA", "XXX XXX XXXX", "🇺🇸")
)